package org.mjjaen.datastructure.graphs.examples;

import lombok.extern.slf4j.Slf4j;
import org.mjjaen.datastructure.graphs.WeightedGraph;
import org.mjjaen.datastructure.graphs.impl.AdjacencyListWeightedGraph;
import org.mjjaen.datastructure.graphs.impl.AdjacencyMatrixWeightedGraph;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class WeightedUndirectedGraphExample extends GraphExample {
    @Override
    public void run() {
        log.info("Creating general vertex ...");
        log.info("Testing adjacency matrix unweighted undirected graph ...");
        WeightedGraph<String> weightedUndirectedGraph = new AdjacencyMatrixWeightedGraph<>(8, false);
        prepareGraph(weightedUndirectedGraph);
        test(weightedUndirectedGraph);
        log.info("Testing adjacency list unweighted undirected graph ...");
        WeightedGraph<String> weightedUndirectedGraph2 = new AdjacencyListWeightedGraph<>(8, false);
        prepareGraph(weightedUndirectedGraph2);
        test(weightedUndirectedGraph2);
    }

    private void prepareGraph(WeightedGraph<String> weightedUndirectedGraph) {
        weightedUndirectedGraph.addVertex(vertexA);
        weightedUndirectedGraph.addVertex(vertexB);
        weightedUndirectedGraph.addVertex(vertexC);
        weightedUndirectedGraph.addVertex(vertexD);
        weightedUndirectedGraph.addVertex(vertexE);
        weightedUndirectedGraph.addVertex(vertexF);
        weightedUndirectedGraph.addVertex(vertexG);
        weightedUndirectedGraph.addVertex(vertexH);
        weightedUndirectedGraph.addEdge(vertexA, vertexB, 5);
        weightedUndirectedGraph.addEdge(vertexB, vertexC, 10);
        weightedUndirectedGraph.addEdge(vertexB, vertexH, 15);
        weightedUndirectedGraph.addEdge(vertexC, vertexE, 20);
        weightedUndirectedGraph.addEdge(vertexC, vertexD, 25);
        weightedUndirectedGraph.addEdge(vertexH, vertexE, 30);
        weightedUndirectedGraph.addEdge(vertexE, vertexF, 35);
        weightedUndirectedGraph.addEdge(vertexE, vertexG, 40);
    }

    private void test(WeightedGraph<String> weightedUndirectedGraph) {
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexA);
        assert null != weightedUndirectedGraph.getEdge(vertexA, vertexB);
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexA, vertexH);
        assert null != weightedUndirectedGraph.getEdge(vertexB, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexB, vertexB);
        assert null != weightedUndirectedGraph.getEdge(vertexB, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexB, vertexD);
        assert null == weightedUndirectedGraph.getEdge(vertexB, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexB, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexB, vertexG);
        assert null != weightedUndirectedGraph.getEdge(vertexB, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexC, vertexA);
        assert null != weightedUndirectedGraph.getEdge(vertexC, vertexB);
        assert null == weightedUndirectedGraph.getEdge(vertexC, vertexC);
        assert null != weightedUndirectedGraph.getEdge(vertexC, vertexD);
        assert null != weightedUndirectedGraph.getEdge(vertexC, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexC, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexC, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexC, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexB);
        assert null != weightedUndirectedGraph.getEdge(vertexD, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexD);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexD, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexB);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexD);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexE);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexF);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexG);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexB);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexD);
        assert null != weightedUndirectedGraph.getEdge(vertexF, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexF, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexB);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexD);
        assert null != weightedUndirectedGraph.getEdge(vertexG, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexH, vertexA);
        assert null != weightedUndirectedGraph.getEdge(vertexH, vertexB);
        assert null == weightedUndirectedGraph.getEdge(vertexH, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexH, vertexD);
        assert null != weightedUndirectedGraph.getEdge(vertexH, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexH, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexH, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexH, vertexH);

        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexA);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexA).get(vertexB) == 5;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexC);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexC);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexE);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexA).containsKey(vertexH);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexB).get(vertexA) == 5;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexB).containsKey(vertexB);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexB).get(vertexC) == 10;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexB).containsKey(vertexD);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexB).containsKey(vertexE);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexB).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexB).containsKey(vertexG);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexB).get(vertexH) == 15;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexC).containsKey(vertexA);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexC).get(vertexB) == 10;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexC).containsKey(vertexC);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexC).get(vertexD) == 25;
        assert weightedUndirectedGraph.getAdjacentWeights(vertexC).get(vertexE) == 20;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexC).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexC).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexC).containsKey(vertexH);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexA);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexB);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexD).get(vertexC) == 25;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexD);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexE);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexD).containsKey(vertexH);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexA);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexB);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexC) == 20;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexD);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexE);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexF) == 35;
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexG) == 40;
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexH) == 30;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexA);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexB);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexC);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexD);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexF).get(vertexE) == 35;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexF).containsKey(vertexH);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexA);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexB);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexC);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexD);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexG).get(vertexE) == 40;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexH);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexH).containsKey(vertexA);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexH).get(vertexB) == 15;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexH).containsKey(vertexC);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexH).containsKey(vertexD);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexH).get(vertexE) == 30;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexH).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexH).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexH).containsKey(vertexH);

        weightedUndirectedGraph.removeEdge(vertexE, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexB);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexD);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexE);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexE, vertexG);
        assert null != weightedUndirectedGraph.getEdge(vertexE, vertexH);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexA);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexB);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexC);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexD);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexE);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexF);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexG);
        assert null == weightedUndirectedGraph.getEdge(vertexG, vertexH);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexB);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexC) == 20;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexD);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexE);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexF) == 35;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexE).containsKey(vertexG);
        assert weightedUndirectedGraph.getAdjacentWeights(vertexE).get(vertexH) == 30;
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexA);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexB);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexC);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexD);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexE);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexF);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexG);
        assert !weightedUndirectedGraph.getAdjacentWeights(vertexG).containsKey(vertexH);
    }
}
